version: "3.8"

services:
  frontend:
    build:
      context: ./catalog-frontend
      dockerfile: Dockerfile
    ports:
      - "3031:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./catalog-backend
      dockerfile: Dockerfile
    ports:
      - "3033:3033"
    environment:
      - MONGO_URI=mongodb://mongo:27017/catalogDB
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: catalog-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
